FROM ubuntu
RUN apt update && apt install build-essential -y && apt-get install gcc-multilib -y   
COPY lab3_sms.cpp .
RUN gcc -fno-pie -no-pie lab3_sms.cpp -o lab3_7171_sms -g -lstdc++  
CMD ./lab3_7171_sms

